title: Arup Dey
logo: "image/arup1.jpg"
#description: text below image
show_download: false
email: "ipe.arup@gmail.com"
location: "New Mexico, USA"

theme: jekyll-theme-minimal


<meta http-equiv='cache-control' content='no-cache'> 
<meta http-equiv='expires' content='0'> 
<meta http-equiv='pragma' content='no-cache'>
